# frozen_string_literal: true

CATEGORIES = {
  GENERAL_INFORMATION: :general_information,
  EDUCATION_AND_TRAINING: :education_and_training,
  BOARD_CERTIFICATION: :board_certification,
  PROFESSIONAL_LICENSE: :professional_license,
  PROFESSIONAL_LIABILITY_INSURANCE_DETAILS: :professional_liability_insurance_details,
  MEDICAL_LICENSING_EXAMINATION: :medical_licensing_examination,
  PEER_REFERENCE: :peer_reference,
  OTHER_CERTIFICATION: :other_certification,
  HEALTHCARE_FACILITY_AFFILIATION: :healthcare_facility_affiliation,
  HOSPITAL_AFFILIATION: :hospital_affiliation,
  ACADEMIC_APPOINTMENT: :academic_appointment,
  RESEARCH_AND_PUBLIC_BENEFIT_DATA: :research_and_public_benefit_data,
  PPD_OR_VACCINATION: :ppd_or_vaccination,
  EMPLOYMENT_HISTORY: :employment_history
}.freeze

CATEGEGORY_ENUM = {
  CATEGORIES[:GENERAL_INFORMATION] => 0,
  CATEGORIES[:EDUCATION_AND_TRAINING] => 1,
  CATEGORIES[:BOARD_CERTIFICATION] => 2,
  CATEGORIES[:PROFESSIONAL_LICENSE] => 3,
  CATEGORIES[:PROFESSIONAL_LIABILITY_INSURANCE_DETAILS] => 4,
  CATEGORIES[:MEDICAL_LICENSING_EXAMINATION] => 5,
  CATEGORIES[:PEER_REFERENCE] => 6,
  CATEGORIES[:OTHER_CERTIFICATION] => 7,
  CATEGORIES[:HEALTHCARE_FACILITY_AFFILIATION] => 8,
  CATEGORIES[:HOSPITAL_AFFILIATION] => 9,
  CATEGORIES[:ACADEMIC_APPOINTMENT] => 10,
  CATEGORIES[:RESEARCH_AND_PUBLIC_BENEFIT_DATA] => 11,
  CATEGORIES[:PPD_OR_VACCINATION] => 12,
  CATEGORIES[:EMPLOYMENT_HISTORY] => 13
}.freeze
