# frozen_string_literal: true

DOCUMENT_KINDS = {
  STATE_DRIVERS_LICENSE_OR_ID: :state_drivers_license_or_id,
  PASSPORT: :passport,
  DD214: :dd214,
  UNDERGRADUATE_DIPLOMA: :undergraduate_diploma,
  MEDICAL_SCHOOL_DIPLOMA: :medical_school_diploma,
  OSTEOPATHIC_SCHOOL_DIPLOMA: :osteopathic_school_diploma,
  OTHER_PROFESSIONAL_SCHOOL_DIPLOMA: :other_professional_school_diploma,
  INTERNSHIP_CERTIFICATE: :internship_certificate,
  RESIDENCY_CERTIFICATE: :residency_certificate,
  FELLOWSHIP_CERTIFICATE: :fellowship_certificate,
  BOARD_CERTIFICATION: :board_certification,
  PHYSICIAN_STATE_MEDICAL_LICENSE: :physician_state_medical_license,
  PHYSICIAN_STATE_FLUOROSCOPY_LICENSE: :physician_state_fluoroscopy_license,
  DRUG_ENFORCEMENT_AGENCY: :drug_enforcement_agency,
  OTHER_STATE_PROFESSIONAL_LICENSE: :other_state_professional_license,
  CERTIFICATION_CARD: :certification_card,
  MALPRACTICE_CERTIFICATE_OF_INSURANCE: :malpractice_certificate_of_insurance,
  CONTINUING_MEDICAL_EDUCATION: :continuing_medical_education,
  CURRICULUM_VITAE: :curriculum_vitae,
  OTHER: :other
}.freeze

DOCUMENT_KIND_ENUM = {
  DOCUMENT_KINDS[:STATE_DRIVERS_LICENSE_OR_ID] => 0,
  DOCUMENT_KINDS[:PASSPORT] => 1,
  DOCUMENT_KINDS[:DD214] => 2,
  DOCUMENT_KINDS[:UNDERGRADUATE_DIPLOMA] => 3,
  DOCUMENT_KINDS[:MEDICAL_SCHOOL_DIPLOMA] => 4,
  DOCUMENT_KINDS[:OSTEOPATHIC_SCHOOL_DIPLOMA] => 5,
  DOCUMENT_KINDS[:OTHER_PROFESSIONAL_SCHOOL_DIPLOMA] => 6,
  DOCUMENT_KINDS[:INTERNSHIP_CERTIFICATE] => 7,
  DOCUMENT_KINDS[:RESIDENCY_CERTIFICATE] => 8,
  DOCUMENT_KINDS[:FELLOWSHIP_CERTIFICATE] => 9,
  DOCUMENT_KINDS[:BOARD_CERTIFICATION] => 10,
  DOCUMENT_KINDS[:PHYSICIAN_STATE_MEDICAL_LICENSE] => 11,
  DOCUMENT_KINDS[:PHYSICIAN_STATE_FLUOROSCOPY_LICENSE] => 12,
  DOCUMENT_KINDS[:DRUG_ENFORCEMENT_AGENCY] => 13,
  DOCUMENT_KINDS[:OTHER_STATE_PROFESSIONAL_LICENSE] => 14,
  DOCUMENT_KINDS[:CERTIFICATION_CARD] => 15,
  DOCUMENT_KINDS[:MALPRACTICE_CERTIFICATE_OF_INSURANCE] => 16,
  DOCUMENT_KINDS[:CONTINUING_MEDICAL_EDUCATION] => 17,
  DOCUMENT_KINDS[:CURRICULUM_VITAE] => 18,
  DOCUMENT_KINDS[:OTHER] => 19
}.freeze
